### ISSUE TITLE
Bug - ScrollerViewPager

### ISSUE THREAD

**Issue by TurKurT656** [chenupt/SpringIndicator#2]
Hi,
Thnx for this awesome lib. I added this lib with Gradle but i cant import ScrollerViewPager. its seems that this view isnt available with Gradle :(

**Comment by chenupt** [comment]
I'm sorry, i have release 1.0.1 just now. But it will take about 2 hours for syncing to maven central.
You can use a normal ViewPager instead of [ScrollViewPager](https://github.com/chenupt/SpringIndicator/blob/master/lib/src/main/java/github/chenupt/springindicator/viewpager/ScrollerViewPager.java) which just is fixed the scroll speed.
